sprites.onCreated(SpriteKind.Enemy, function (sprite) {
    sprite.x = randint(0, 100)
})
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    mySprite.vy += -5
})
sprites.onCreated(SpriteKind.Food, function (sprite) {
    sprite.x = randint(0, 100)
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    mySprite.vx += -5
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    mySprite.vx += 5
})
sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Player, function (sprite, otherSprite) {
    info.setLife(3)
    mySprite3.follow(mySprite, 20)
})
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    mySprite.vy += 5
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    info.changeScoreBy(1)
    info.startCountdown(10)
    mySprite2.setPosition(randint(10, 160), randint(10, 120))
    mySprite.setStayInScreen(true)
})
let mySprite3: Sprite = null
let mySprite2: Sprite = null
let mySprite: Sprite = null
scene.setBackgroundColor(9)
game.splash("Motion Project Game")
mySprite = sprites.create(img`
    ......ffff..............
    ....fff22fff............
    ...fff2222fff...........
    ..fffeeeeeefff..........
    ..ffe222222eef..........
    ..fe2ffffff2ef..........
    ..ffffeeeeffff......ccc.
    .ffefbf44fbfeff....cddc.
    .ffefbf44fbfeff...cddc..
    .fee4dddddd4eef.ccddc...
    fdfeeddddd4eeffecddc....
    fbffee4444ee4fddccc.....
    fbf4f222222f1edde.......
    fcf.f222222f44ee........
    .ff.f445544f............
    ....ffffffff............
    .....ff..ff.............
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
mySprite.x += -1 * 1
mySprite.x = 75
mySprite.y = 75
mySprite2 = sprites.create(assets.image`Tree`, SpriteKind.Food)
mySprite3 = sprites.create(assets.image`Snake`, SpriteKind.Enemy)
